var wiMap = {
    "848180": {
       "Type": "work_item",
       "Name": "As a user i would like to generate report according to the settings",
       "Id": "848180",
       "Last_Modified": "2019-08-07T13:03:50Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "883015": {
       "Type": "work_item",
       "Name": "As a user I would like to have an option to define order by in generate report",
       "Id": "883015",
       "Last_Modified": "2019-08-20T14:58:18Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "853057": {
       "Type": "work_item",
       "Name": "As a user i would  like to perform action on the printed entities (i.e. duplicate, delete, clear selected fields)",
       "Id": "853057",
       "Last_Modified": "2019-08-12T08:39:28Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "798056": {
       "Type": "work_item",
       "Name": "Create and productize report generator resource (should be implemented as public api resource)",
       "Id": "798056",
       "Last_Modified": "2019-08-22T06:47:06Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "In Testing",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "877050": {
       "Type": "work_item",
       "Name": "as an admin i want fields dropdown will be multi value selection",
       "Id": "877050",
       "Last_Modified": "2019-08-07T13:00:11Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "881022": {
       "Type": "work_item",
       "Name": "as an admin i want to save report configuration as template and load existing templates",
       "Id": "881022",
       "Last_Modified": "2019-08-20T14:57:04Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Fixing Defects",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "878036": {
       "Type": "work_item",
       "Name": "as a user I would like to select the orientation of the report (portrait or landscape) - should be with icon",
       "Id": "878036",
       "Last_Modified": "2019-08-14T10:45:54Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845119": {
       "Type": "work_item",
       "Name": "As an admin i want define which entities to print (content tab)",
       "Id": "845119",
       "Last_Modified": "2019-08-06T11:22:16Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "853058": {
       "Type": "work_item",
       "Name": "Add experiment to show report configuration screen",
       "Id": "853058",
       "Last_Modified": "2019-08-08T09:30:16Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "833069": {
       "Type": "work_item",
       "Name": "add group by functionality [including multi value] to reporting mechanism",
       "Id": "833069",
       "Last_Modified": "2019-07-23T08:03:34Z",
       "Blocked": "False",
       "Subtype": "story",
       "Phase": "New",
       "Parent": "#787251 - [Document Report] Child level entities - Add child entities (1 level) in the report settings by selecting predefined relation",
       "Author": "Eli Emanuel",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "798061": {
       "Type": "work_item",
       "Name": "report configuration persistance managment - ui",
       "Id": "798061",
       "Last_Modified": "2019-08-06T11:26:59Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "888026": {
       "Type": "work_item",
       "Name": "Add experiment and change test name in case of failure in BeforeClass",
       "Id": "888026",
       "Last_Modified": "2019-08-19T11:14:25Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Elena Fradkin",
       "Phase": "Ready for QA",
       "Parent": "#878010 - [Test Injection] Failed Before Class Should ensure that all tests in the class fail",
       "Author": "Elena Fradkin",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "782026": {
       "Type": "work_item",
       "Name": "Remove Experiment for: Support Favorites in the Pipeline module",
       "Id": "782026",
       "Last_Modified": "2019-07-10T11:24:53Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#868033 - [Tech] Remove and add Samet Experiments - Manchester",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "854058": {
       "Type": "work_item",
       "Name": "As a user i want to set the order of the entities to print",
       "Id": "854058",
       "Last_Modified": "2019-08-08T11:43:16Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "851017": {
       "Type": "work_item",
       "Name": "add report configuration tree",
       "Id": "851017",
       "Last_Modified": "2019-08-07T12:58:22Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "782027": {
       "Type": "work_item",
       "Name": "Remove Experiment for: Support Favorites in the Pipeline module",
       "Id": "782027",
       "Last_Modified": "2019-08-14T11:08:03Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Parent": "#868033 - [Tech] Remove and add Samet Experiments - Manchester",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "882019": {
       "Type": "work_item",
       "Name": "As an user I would like to title, summary, author and generated on date will be added as an open page to the generated report file",
       "Id": "882019",
       "Last_Modified": "2019-08-12T12:42:27Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "782028": {
       "Type": "work_item",
       "Name": "Remove Experiment for: [DevSecOps] Add OOTB widget - Features with open critical vulnerabilities",
       "Id": "782028",
       "Last_Modified": "2019-07-10T11:24:53Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Parent": "#868033 - [Tech] Remove and add Samet Experiments - Manchester",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845121": {
       "Type": "work_item",
       "Name": "As an admin i would like to filter which entities i want to see in the report (content tab)",
       "Id": "845121",
       "Last_Modified": "2019-08-08T12:08:47Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845118": {
       "Type": "work_item",
       "Name": "As an admin i would like to open report config from setting menu",
       "Id": "845118",
       "Last_Modified": "2019-08-12T14:21:38Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "887017": {
       "Type": "work_item",
       "Name": "change file format to be dropdown and redesign order by dropdown",
       "Id": "887017",
       "Last_Modified": "2019-08-19T06:13:31Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "888006": {
       "Type": "work_item",
       "Name": "Continuation of Tech - Report configuration should be lazy loaded",
       "Id": "888006",
       "Last_Modified": "2019-08-15T13:07:57Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "854060": {
       "Type": "work_item",
       "Name": "Remove experiment for UI report configuration",
       "Id": "854060",
       "Last_Modified": "2019-08-04T10:27:28Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Ready for R&D",
       "Parent": "#868033 - [Tech] Remove and add Samet Experiments - Manchester",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "888027": {
       "Type": "work_item",
       "Name": "remove experiment \"failure-in-before-class-experiment\"",
       "Id": "888027",
       "Last_Modified": "2019-08-18T13:07:52Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Elena Fradkin",
       "Phase": "New",
       "Parent": "#878010 - [Test Injection] Failed Before Class Should ensure that all tests in the class fail",
       "Author": "Elena Fradkin",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845122": {
       "Type": "work_item",
       "Name": "As an admin i want to select which fields to see in the reports",
       "Id": "845122",
       "Last_Modified": "2019-08-12T10:52:13Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "863069": {
       "Type": "work_item",
       "Name": "as an admin i want to set the order of the fields (by drag and drop) (content tab)",
       "Id": "863069",
       "Last_Modified": "2019-08-08T11:31:35Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Fixing Defects",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "877003": {
       "Type": "work_item",
       "Name": "as an admin i want to see error dialog when user exceeded fuses",
       "Id": "877003",
       "Last_Modified": "2019-08-08T11:31:53Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "875131": {
       "Type": "work_item",
       "Name": "as an admin i want to see the  create document report menu button only when i have a permission to generate report configuration",
       "Id": "875131",
       "Last_Modified": "2019-08-14T07:39:11Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "884022": {
       "Type": "work_item",
       "Name": "As an admin i would like to add a title, author and generated on date to the report (Attribute tab)",
       "Id": "884022",
       "Last_Modified": "2019-08-22T05:20:45Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845120": {
       "Type": "work_item",
       "Name": "As an admin i would like to decide in which format i would like to print (grid or details) (content tab)",
       "Id": "845120",
       "Last_Modified": "2019-08-12T14:24:10Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "878001": {
       "Type": "work_item",
       "Name": "As an admin i would like to add a file name and format to the report (Attribute tab)",
       "Id": "878001",
       "Last_Modified": "2019-08-07T12:59:55Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "846125": {
       "Type": "work_item",
       "Name": "As an admin i would like to add a summary, author and generated on date to the report (Attribute tab)",
       "Id": "846125",
       "Last_Modified": "2019-08-15T07:48:49Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "883014": {
       "Type": "work_item",
       "Name": "Generate Report - UI - table / details toggle button should be with icons",
       "Id": "883014",
       "Last_Modified": "2019-08-14T10:46:24Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "881027": {
       "Type": "work_item",
       "Name": "Generate Report - UI - sub type field should be added to the default fields for all the relevant entities",
       "Id": "881027",
       "Last_Modified": "2019-08-20T15:05:32Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "853022": {
       "Type": "work_item",
       "Name": "Tech - Report configuration should be lazy loaded",
       "Id": "853022",
       "Last_Modified": "2019-08-15T13:02:31Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Ready for QA",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Nir Yom Tov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "866013": {
       "Type": "work_item",
       "Name": "[Document Report] Be able to save and reuse report settings - change Experiment to On",
       "Id": "866013",
       "Last_Modified": "2019-07-10T11:24:53Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#868033 - [Tech] Remove and add Samet Experiments - Manchester",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "874080": {
       "Type": "work_item",
       "Name": "support duplicate entities in report configuration",
       "Id": "874080",
       "Last_Modified": "2019-08-14T07:49:44Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Moshe Golan",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "882018": {
       "Type": "work_item",
       "Name": "Generate Report - UI - need to change Add section instead of add entity",
       "Id": "882018",
       "Last_Modified": "2019-08-14T10:46:11Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "884021": {
       "Type": "work_item",
       "Name": "turn on the experiment (open the rest for document report)",
       "Id": "884021",
       "Last_Modified": "2019-08-22T05:23:11Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "887016": {
       "Type": "work_item",
       "Name": "turn on hash_including_release_and_milestone experiment in production",
       "Id": "887016",
       "Last_Modified": "2019-08-20T12:36:13Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "Ready for QA",
       "Parent": "#845216 - Add Release and Milestone to Unique Identifier for Automated Run",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "883016": {
       "Type": "work_item",
       "Name": "Generate Report - UI - fields section should have a clear all fields button inside of it",
       "Id": "883016",
       "Last_Modified": "2019-08-22T05:21:30Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "878098": {
       "Type": "work_item",
       "Name": "need to remove the generate report buttons from the grid toolbar - need to put them under new experiment (Dev true)",
       "Id": "878098",
       "Last_Modified": "2019-08-20T15:10:43Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "881026": {
       "Type": "work_item",
       "Name": "Generate Report - reference field in the generated  report should appear with ID+Name",
       "Id": "881026",
       "Last_Modified": "2019-08-20T14:44:27Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "In Testing",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "854059": {
       "Type": "work_item",
       "Name": "[tech] reader module of report generator should calculate and retun the amount of entities",
       "Id": "854059",
       "Last_Modified": "2019-07-30T20:54:38Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Eli Emanuel",
       "Phase": "Done",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "877140": {
       "Type": "work_item",
       "Name": "Warn user before modifying the release or milestone in a pipeline",
       "Id": "877140",
       "Last_Modified": "2019-08-06T12:27:38Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Parent": "#877080 - Warn user before modifying the release or milestone in a pipeline",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "852013": {
       "Type": "work_item",
       "Name": "only report creator should have access for download generated report",
       "Id": "852013",
       "Last_Modified": "2019-08-19T11:05:02Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Nadav Hames",
       "Phase": "In Testing",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "798059": {
       "Type": "work_item",
       "Name": "Memory consumption of Aspose writer (prevent DOS) need to checked and take under consideration",
       "Id": "798059",
       "Last_Modified": "2019-08-06T14:41:05Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "Done",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "882017": {
       "Type": "work_item",
       "Name": "As a user I would like generate report UI header section text to be aligned with the tree text",
       "Id": "882017",
       "Last_Modified": "2019-08-12T12:35:20Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "886001": {
       "Type": "work_item",
       "Name": "[Tech]: only report creator should have access for download generated report - should change it to be platform + add admin permissions to access the attachment",
       "Id": "886001",
       "Last_Modified": "2019-08-15T08:04:19Z",
       "Blocked": "False",
       "Subtype": "story",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Parent": "#787250 - [Document Report] Define format (word/pdf), header, footer, logo and OOTB placeholders in the report settings + UI improvments",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Ohad Samet",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "832071": {
       "Type": "work_item",
       "Name": "Add Rest automation - Productization (permissions, performance fuze admin parameter, localization)",
       "Id": "832071",
       "Last_Modified": "2019-07-03T10:40:58Z",
       "Blocked": "False",
       "Subtype": "quality_story",
       "Phase": "New",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (12.60.41)",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "833075": {
       "Type": "work_item",
       "Name": "Add Rest automation - Link automated runs injected via pipelines to Milestones",
       "Id": "833075",
       "Last_Modified": "2019-08-06T12:27:27Z",
       "Blocked": "False",
       "Subtype": "quality_story",
       "Owner": "Zvi Fried",
       "Phase": "Done",
       "Parent": "#786047 - Link automated runs injected via pipelines to Milestones",
       "Milestone": "Push01 (12.60.41)",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "832069": {
       "Type": "work_item",
       "Name": "Add UI automation - Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Id": "832069",
       "Last_Modified": "2019-07-03T10:40:59Z",
       "Blocked": "False",
       "Subtype": "quality_story",
       "Phase": "New",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (12.60.41)",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "878011": {
       "Type": "work_item",
       "Name": "Add Rest automation - Ensure that New Automated Run is created when pipeline milestone/release is changed",
       "Id": "878011",
       "Last_Modified": "2019-08-06T06:29:21Z",
       "Blocked": "False",
       "Subtype": "quality_story",
       "Owner": "Zvi Fried",
       "Phase": "Done",
       "Parent": "#845216 - Add Release and Milestone to Unique Identifier for Automated Run",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Finkelstein",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "877080": {
       "Type": "work_item",
       "Name": "Warn user before modifying the release or milestone in a pipeline",
       "Id": "877080",
       "Last_Modified": "2019-08-14T11:32:51Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Nir Yom Tov",
       "Phase": "Design",
       "Parent": "#792067 - Testing flow",
       "Milestone": "Push02 (15.0.14)",
       "Author": "Yael Peisachov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "786047": {
       "Type": "work_item",
       "Name": "Link automated runs injected via pipelines to Milestones",
       "Id": "786047",
       "Last_Modified": "2019-08-21T03:22:12Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Nir Yom Tov",
       "Phase": "Done",
       "Parent": "#793058 - Regression test planning",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Yael Peisachov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "845216": {
       "Type": "work_item",
       "Name": "Add Release and Milestone to Unique Identifier for Automated Run",
       "Id": "845216",
       "Last_Modified": "2019-08-20T06:05:58Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Nir Yom Tov",
       "Phase": "Exposed",
       "Parent": "#793058 - Regression test planning",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Finkelstein",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "868033": {
       "Type": "work_item",
       "Name": "[Tech] Remove and add Samet Experiments - Manchester",
       "Id": "868033",
       "Last_Modified": "2019-07-24T06:08:11Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Parent": "#511008 - DevSecOps",
       "Author": "Daniel Finkelstein",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "787252": {
       "Type": "work_item",
       "Name": "[Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Id": "787252",
       "Last_Modified": "2019-08-19T07:14:40Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Daniel Shmaya",
       "Phase": "In Testing",
       "Parent": "#793073 - Document reports",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Yael Peisachov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "786205": {
       "Type": "work_item",
       "Name": "[Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Id": "786205",
       "Last_Modified": "2019-08-20T13:02:41Z",
       "Blocked": "False",
       "Subtype": "feature",
       "Owner": "Nir Yom Tov",
       "Phase": "In Testing",
       "Parent": "#793073 - Document reports",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Yael Peisachov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops"
    },
    "751081": {
       "Type": "work_item",
       "Name": "Long name in Pipeline run is cut and ellipses are missing",
       "Id": "751081",
       "Last_Modified": "2019-08-21T10:42:27Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Duplicate",
       "Severity": "Low",
       "Parent": "#755128 - [Tech] [Pipelines] UI State Refactoring to improve module Performance",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "874025": {
       "Type": "work_item",
       "Name": "Performance : Query on scm_commit take 17 sec in Center",
       "Id": "874025",
       "Last_Modified": "2019-08-21T10:43:36Z",
       "Blocked": "True",
       "Subtype": "defect",
       "Blocked_Reason": "Waiting for the purging feature to fix it",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "High",
       "Parent": "#246004 - Pipeline area performance",
       "Author": "Dani Levi",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "874026": {
       "Type": "work_item",
       "Name": "Performance  : query on CI_BUILD take more then 18 sec in Center.",
       "Id": "874026",
       "Last_Modified": "2019-08-21T10:43:36Z",
       "Blocked": "True",
       "Subtype": "defect",
       "Blocked_Reason": "Waiting for the purging feature to fix it",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "High",
       "Parent": "#246004 - Pipeline area performance",
       "Author": "Dani Levi",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "862062": {
       "Type": "work_item",
       "Name": "pipeline assinged test notification reports wrong number of assigned tests when tests are failing in before class",
       "Id": "862062",
       "Last_Modified": "2019-08-21T08:59:34Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Fixed",
       "Severity": "Medium",
       "Parent": "#878010 - [Test Injection] Failed Before Class Should ensure that all tests in the class fail",
       "Author": "Alex Shnayder",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "876131": {
       "Type": "work_item",
       "Name": "little typos error in filtrer pipelines by release",
       "Id": "876131",
       "Last_Modified": "2019-08-06T06:05:49Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786047 - Link automated runs injected via pipelines to Milestones",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "879002": {
       "Type": "work_item",
       "Name": "Miss : in the fields in SETTINGS tab",
       "Id": "879002",
       "Last_Modified": "2019-08-12T11:25:26Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Rejected",
       "Severity": "Low",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "877104": {
       "Type": "work_item",
       "Name": "No scrolling option in the entities list",
       "Id": "877104",
       "Last_Modified": "2019-08-12T12:15:31Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "885017": {
       "Type": "work_item",
       "Name": "No prompt when selecting a template as default",
       "Id": "885017",
       "Last_Modified": "2019-08-21T12:09:04Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "867041": {
       "Type": "work_item",
       "Name": "New runs are created instead of adding previous runs to existing ones",
       "Id": "867041",
       "Last_Modified": "2019-08-01T11:40:52Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#845216 - Add Release and Milestone to Unique Identifier for Automated Run",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878003": {
       "Type": "work_item",
       "Name": "No tooltip that states that there is a newer pipeline run",
       "Id": "878003",
       "Last_Modified": "2019-07-30T13:42:16Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878077": {
       "Type": "work_item",
       "Name": "Missing Customize fields button from Pipeline details",
       "Id": "878077",
       "Last_Modified": "2019-08-21T13:14:39Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Opened",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "782007": {
       "Type": "work_item",
       "Name": "Missing navigation buttons between Pipeline Runs",
       "Id": "782007",
       "Last_Modified": "2019-07-30T16:41:03Z",
       "Blocked": "True",
       "Subtype": "defect",
       "Blocked_Reason": "Platform Feature",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "High",
       "Parent": "#878006 - [Pipeline UI] Add Navigation Buttons Between Pipeline Runs",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "874063": {
       "Type": "work_item",
       "Name": "NullCIBuildNumber when rebuilding job twice",
       "Id": "874063",
       "Last_Modified": "2019-08-19T13:08:07Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Opened",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Sprint": "Sprint 1 (15.0.3/15.0.4)",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "874071": {
       "Type": "work_item",
       "Name": "User without edit role can edit pipeline he created",
       "Id": "874071",
       "Last_Modified": "2019-07-31T14:49:15Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Ohad Samet",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878126": {
       "Type": "work_item",
       "Name": "When adding a lot of filed the Add button almost disappears (look at the image inside)",
       "Id": "878126",
       "Last_Modified": "2019-08-19T08:11:55Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "867084": {
       "Type": "work_item",
       "Name": "User without \"Manage Document Report\" cannot view shared report configuration entities.",
       "Id": "867084",
       "Last_Modified": "2019-07-31T14:49:14Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nadav Hames",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#795008 - [Document Report] Be able to save and reuse report settings - Server",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "885012": {
       "Type": "work_item",
       "Name": "Unsorted Fields when adding new udf",
       "Id": "885012",
       "Last_Modified": "2019-08-19T07:39:00Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "875077": {
       "Type": "work_item",
       "Name": "User with Viewer Role and CRUD permisions on Assigment Rule can see the CI Server",
       "Id": "875077",
       "Last_Modified": "2019-08-21T06:29:26Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "881028": {
       "Type": "work_item",
       "Name": "When dragging entity (section) on another entity the fathom is green although you cannot put the entity there",
       "Id": "881028",
       "Last_Modified": "2019-08-14T11:42:22Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "881010": {
       "Type": "work_item",
       "Name": "When generating a report on Octane env. that runs on Linux the PDFs font is changing",
       "Id": "881010",
       "Last_Modified": "2019-08-21T09:26:12Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Opened",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878125": {
       "Type": "work_item",
       "Name": "When generating a report with No headlines of an entity (Section header) it creates default headlines",
       "Id": "878125",
       "Last_Modified": "2019-08-22T05:21:34Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "846031": {
       "Type": "work_item",
       "Name": "When generating a doc with the field progress (Epic/Feature)  you get not readable report",
       "Id": "846031",
       "Last_Modified": "2019-07-31T07:38:33Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#853002 - Proper representation of progress and coverage fields in the document report and excel report",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "872067": {
       "Type": "work_item",
       "Name": "When Exporting to word/pdf an entity with wide table inside its description, the table is cut off",
       "Id": "872067",
       "Last_Modified": "2019-07-25T09:13:39Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Vichter",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "877159": {
       "Type": "work_item",
       "Name": "When generatin empty  report you do not get an informative message for the failure",
       "Id": "877159",
       "Last_Modified": "2019-08-14T10:49:22Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878123": {
       "Type": "work_item",
       "Name": "This message (look inside) does not disappear after a few seconds",
       "Id": "878123",
       "Last_Modified": "2019-08-12T12:25:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878110": {
       "Type": "work_item",
       "Name": "run duration displays milliseconds instead of human readable string",
       "Id": "878110",
       "Last_Modified": "2019-08-21T10:36:25Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Duplicate",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Alex Shnayder",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "884014": {
       "Type": "work_item",
       "Name": "Selecting a report template does not fill in the report generator",
       "Id": "884014",
       "Last_Modified": "2019-08-21T12:09:07Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "746001": {
       "Type": "work_item",
       "Name": "When linking BLI to commit in Features BACKLOG ITEMS tab, the relevant fields in Features doc view is updated only after refresh",
       "Id": "746001",
       "Last_Modified": "2019-07-30T16:41:04Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Orit Ifrach",
       "Phase": "Opened",
       "Severity": "Low",
       "Parent": "#700148 - [Commits] Manually Connecting commits to BLIs: Link commits to Stories in Story Grid",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "854085": {
       "Type": "work_item",
       "Name": "Pipeline module high CPU consumption while module not in use",
       "Id": "854085",
       "Last_Modified": "2019-07-31T10:39:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Alex Shnayder",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "814300": {
       "Type": "work_item",
       "Name": "Problem with exporting requirements from Octane to Excel",
       "Id": "814300",
       "Last_Modified": "2019-08-11T07:39:15Z",
       "Blocked": "True",
       "Subtype": "defect",
       "Blocked_Reason": "Not waiting",
       "Phase": "Planned",
       "Severity": "Low",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "SW-RnD Octane Support",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Gent (12.55.17)"
    },
    "885018": {
       "Type": "work_item",
       "Name": "Setting a report template as default is saved only in that browser instance",
       "Id": "885018",
       "Last_Modified": "2019-08-15T12:54:57Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Rejected",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "884015": {
       "Type": "work_item",
       "Name": "The template name used to autofill is not shown at the template dropdown",
       "Id": "884015",
       "Last_Modified": "2019-08-15T12:54:53Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Low",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "838044": {
       "Type": "work_item",
       "Name": "There are times when the status for the first run of a pipeline is not updated in the bucket after the run is completed",
       "Id": "838044",
       "Last_Modified": "2019-07-24T06:46:53Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#786013 - [Tech] Pipeline Module Lazy Loading - performance",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "880010": {
       "Type": "work_item",
       "Name": "The Fields are not sorted",
       "Id": "880010",
       "Last_Modified": "2019-08-14T10:50:04Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "765016": {
       "Type": "work_item",
       "Name": "Single user exp: loading/scrolling backlog items grid when commit files, commits and commiters fields are visible exceeds KPI",
       "Id": "765016",
       "Last_Modified": "2019-07-31T10:39:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Yuri Guller",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Anat Beit Ner",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "881013": {
       "Type": "work_item",
       "Name": "The Drag & Drop in not symmetry from right and left side. The problem is with the left side",
       "Id": "881013",
       "Last_Modified": "2019-08-22T05:20:55Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "876032": {
       "Type": "work_item",
       "Name": "[I18N][Garbled-text]Garbled text exist in exported PDF file for requirement",
       "Id": "876032",
       "Last_Modified": "2019-07-25T10:30:05Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Hao Li Shi",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "862050": {
       "Type": "work_item",
       "Name": "[Jenkins] committer not shown in the build details",
       "Id": "862050",
       "Last_Modified": "2019-08-13T12:11:36Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#389010 - Octane-Slack integration enhancements :: Slack from Pipeline",
       "Author": "Gitit Steingarten",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "833059": {
       "Type": "work_item",
       "Name": "[L10N-truncation]string“There are 6 new runs in this pipeline.” are truncated in JAN / FRA /ESP ENV.",
       "Id": "833059",
       "Last_Modified": "2019-07-31T10:39:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#265137 - UI Localization (L10N) Support",
       "Author": "xiao-min Yu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Liverpool (12.60.47)"
    },
    "883004": {
       "Type": "work_item",
       "Name": "[Document Report] - generated report  TOC font is wrong",
       "Id": "883004",
       "Last_Modified": "2019-08-20T15:05:19Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "884012": {
       "Type": "work_item",
       "Name": "[Document report] Add section drop-down list elements not sorted",
       "Id": "884012",
       "Last_Modified": "2019-08-19T07:27:12Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "884002": {
       "Type": "work_item",
       "Name": "[Document report] Buttons for adding Fields and Filters are different one to the other",
       "Id": "884002",
       "Last_Modified": "2019-08-19T07:25:49Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Low",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "778029": {
       "Type": "work_item",
       "Name": "[Regression Juventus Push02] Scroll to right button is not disabled when there are no more pipelines to be displayed in toolbar",
       "Id": "778029",
       "Last_Modified": "2019-07-30T16:41:01Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "730048": {
       "Type": "work_item",
       "Name": "[Regression Push 3 12.60.21] The label color of a pipeline is changed if the view is switched from Tree to Flat",
       "Id": "730048",
       "Last_Modified": "2019-08-20T15:14:59Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Inter Milano (12.60.21)"
    },
    "831022": {
       "Type": "work_item",
       "Name": "[Samet_XMEN_Liverpool_Push2] Green \"Test\" tag does not appear on the top corner of root job if Testing Environment is set in Topology tab for a pipeline",
       "Id": "831022",
       "Last_Modified": "2019-08-15T09:22:13Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Liverpool (12.60.47)"
    },
    "885030": {
       "Type": "work_item",
       "Name": "[Permissions] Tester can create and edit SCM users",
       "Id": "885030",
       "Last_Modified": "2019-08-21T11:18:23Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Opened",
       "Severity": "High",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push02 (15.0.14)",
       "Author": "Anna Omri",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "888043": {
       "Type": "work_item",
       "Name": "[Pipeline] tests are not shown in the pipeline module",
       "Id": "888043",
       "Last_Modified": "2019-08-22T05:07:39Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Ohad Samet",
       "Phase": "Closed",
       "Severity": "Critical",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "David Milstein",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "821030": {
       "Type": "work_item",
       "Name": "[Regression - Liverpool Push1]  Long name for a pipeline is not displayed properly in Pipeline docview",
       "Id": "821030",
       "Last_Modified": "2019-08-20T13:58:15Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Liverpool (12.60.47)"
    },
    "875072": {
       "Type": "work_item",
       "Name": "[Document Report] - filter doesnt take subtypes into acount",
       "Id": "875072",
       "Last_Modified": "2019-07-29T15:19:51Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Daniel Shmaya",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "868095": {
       "Type": "work_item",
       "Name": "\"order_by\" attribute accepts any value",
       "Id": "868095",
       "Last_Modified": "2019-07-29T13:03:20Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nadav Hames",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#795008 - [Document Report] Be able to save and reuse report settings - Server",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "838049": {
       "Type": "work_item",
       "Name": "#Latest option in navigation dropdown list is not always kept",
       "Id": "838049",
       "Last_Modified": "2019-07-31T10:39:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#786013 - [Tech] Pipeline Module Lazy Loading - performance",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "885054": {
       "Type": "work_item",
       "Name": "copy link toolbar button should appear after selecting a single commit",
       "Id": "885054",
       "Last_Modified": "2019-08-21T13:36:21Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push02 (15.0.14)",
       "Author": "Zvi Vichter",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "861056": {
       "Type": "work_item",
       "Name": "\"Assignment Rule\" button is not responding",
       "Id": "861056",
       "Last_Modified": "2019-08-21T10:30:37Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Fixed",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "864039": {
       "Type": "work_item",
       "Name": "\"failed before class\" test failures should be injected with a dedicated status",
       "Id": "864039",
       "Last_Modified": "2019-08-20T13:58:15Z",
       "Blocked": "True",
       "Subtype": "defect",
       "Blocked_Reason": "Functional Decision",
       "Owner": "Elena Fradkin",
       "Phase": "Duplicate",
       "Severity": "High",
       "Parent": "#878010 - [Test Injection] Failed Before Class Should ensure that all tests in the class fail",
       "Author": "Shai Barashi",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "867085": {
       "Type": "work_item",
       "Name": "\"group_by\" attribute cannot get any value",
       "Id": "867085",
       "Last_Modified": "2019-08-11T07:39:15Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nadav Hames",
       "Phase": "Fixed",
       "Severity": "Medium",
       "Parent": "#795008 - [Document Report] Be able to save and reuse report settings - Server",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "848034": {
       "Type": "work_item",
       "Name": "[Center] Test name is displayed twice  for automated run if MR is also present in details pane for last test runs in fat line view",
       "Id": "848034",
       "Last_Modified": "2019-07-31T10:41:01Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "884011": {
       "Type": "work_item",
       "Name": "[Document report ]First element in Add Section drop-down list  always highlighted",
       "Id": "884011",
       "Last_Modified": "2019-08-21T09:07:57Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Phase": "Rejected",
       "Severity": "Low",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "889001": {
       "Type": "work_item",
       "Name": "[Document report]  Empty template can be saved",
       "Id": "889001",
       "Last_Modified": "2019-08-21T13:10:19Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Fixed",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "875137": {
       "Type": "work_item",
       "Name": "Designer field in Test Suite -> test tab is wired printed",
       "Id": "875137",
       "Last_Modified": "2019-07-29T11:58:40Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#755105 - [Document Report] Export grid of defects to Word (plain grid, no extras, export visible columns, according to filter), user gets notification when ready",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "854101": {
       "Type": "work_item",
       "Name": "Subtype fields in all entities should be displayed as in grid and not with an underscore",
       "Id": "854101",
       "Last_Modified": "2019-08-12T12:39:08Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#787252 - [Document Report] Productization (permissions, performance fuze admin parameter, localization)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "787170": {
       "Type": "work_item",
       "Name": "[CENTER] Branch information is missing in the Repositories field of a commit",
       "Id": "787170",
       "Last_Modified": "2019-07-30T16:41:04Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "New",
       "Severity": "High",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Ehud Michelson",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Liverpool (12.60.47)"
    },
    "830010": {
       "Type": "work_item",
       "Name": "[Samet_XMEN_Liverpool_Push2] In automated run details tab, \"Linked Defect\" field value does not link to the defect",
       "Id": "830010",
       "Last_Modified": "2019-07-31T10:39:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Liverpool (12.60.47)"
    },
    "885015": {
       "Type": "work_item",
       "Name": "Exception when saving empty template",
       "Id": "885015",
       "Last_Modified": "2019-08-19T11:19:54Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "863032": {
       "Type": "work_item",
       "Name": "Favorite icon is not correctly displayed in Pipelines menu",
       "Id": "863032",
       "Last_Modified": "2019-07-31T10:41:01Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "880002": {
       "Type": "work_item",
       "Name": "Fileds In Topology tab of a Pipeline --> configuration Dialog --> TEST FIELDS tab  are not aligned",
       "Id": "880002",
       "Last_Modified": "2019-08-08T10:58:01Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "877116": {
       "Type": "work_item",
       "Name": "error on missing milestone field on nav to runs tab in pipeline doc view",
       "Id": "877116",
       "Last_Modified": "2019-08-07T17:19:06Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Duplicate",
       "Severity": "Critical",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Alex Shnayder",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "877082": {
       "Type": "work_item",
       "Name": "Error when filter pipelines by milestone and then turning off the  link_test_run_to_milestone experiment",
       "Id": "877082",
       "Last_Modified": "2019-08-05T13:55:07Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Critical",
       "Parent": "#786047 - Link automated runs injected via pipelines to Milestones",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "882049": {
       "Type": "work_item",
       "Name": "Exception dialog appears when trying to drag and drop the single Field remained",
       "Id": "882049",
       "Last_Modified": "2019-08-19T07:14:07Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "878068": {
       "Type": "work_item",
       "Name": "Increase max length (currently 255) of scm-commit message (comment)",
       "Id": "878068",
       "Last_Modified": "2019-08-11T07:39:15Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Elena Fradkin",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "726028": {
       "Type": "work_item",
       "Name": "Link to Vulnerability navigate you into Vulnerability doc view when have no permission",
       "Id": "726028",
       "Last_Modified": "2019-08-20T15:14:59Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Opened",
       "Severity": "Medium",
       "Parent": "#644078 - [DevSecOps] [Data Visibility] Data visibility for Vulnerabilities per role",
       "Author": "Dan Moscowitch",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Inter Milano (12.60.21)"
    },
    "875050": {
       "Type": "work_item",
       "Name": "link_commit_to_story_manually still present",
       "Id": "875050",
       "Last_Modified": "2019-08-20T14:58:46Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#781001 - [Tech] Remove and add Samet Experiments - Munich",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "754052": {
       "Type": "work_item",
       "Name": "If Filter by Release is active and a new pipeline is created in that release, it is not displayed in pipeline toolbar",
       "Id": "754052",
       "Last_Modified": "2019-07-30T16:41:03Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#755128 - [Tech] [Pipelines] UI State Refactoring to improve module Performance",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Juventus (12.60.35)"
    },
    "848035": {
       "Type": "work_item",
       "Name": "In Add Pipeline Dialog, custom brunch type has _ in its name (see image inside)",
       "Id": "848035",
       "Last_Modified": "2019-08-21T16:41:11Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Daniel Shmaya",
       "Phase": "Rejected",
       "Severity": "Low",
       "Parent": "#617033 - [Pipelines] Continuation of Compare Test Failures Between Pipeline runs( POC / TP)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "881055": {
       "Type": "work_item",
       "Name": "In Automatic Runs, the duration field should show time in HH:MM:SS.sss format",
       "Id": "881055",
       "Last_Modified": "2019-08-12T12:32:45Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "David Gruzman",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "881016": {
       "Type": "work_item",
       "Name": "Drag and Drop does not work on Firefox browser",
       "Id": "881016",
       "Last_Modified": "2019-08-20T13:58:15Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "Closed",
       "Severity": "Critical",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "881015": {
       "Type": "work_item",
       "Name": "An Exception is thrown When trying to add the same entity to the tree",
       "Id": "881015",
       "Last_Modified": "2019-08-12T13:12:02Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Critical",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "849044": {
       "Type": "work_item",
       "Name": "Automated run document view - Milestone should come right after Release in the default form",
       "Id": "849044",
       "Last_Modified": "2019-08-08T11:17:54Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Yael Peisachov",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "875094": {
       "Type": "work_item",
       "Name": "Automated Runs dont appear in Test tab when running a pipeline in prod environment",
       "Id": "875094",
       "Last_Modified": "2019-07-29T12:22:13Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Bianca Claudia Chiorean",
       "Release": "Manchester-United",
       "Sprint": "Sprint 1 (15.0.3/15.0.4)",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "604005": {
       "Type": "work_item",
       "Name": "[To Fix] [L10N][Truncation] truncation issue in Pipelines Topologie UI",
       "Id": "604005",
       "Last_Modified": "2019-08-14T07:54:29Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Medium",
       "Parent": "#265137 - UI Localization (L10N) Support",
       "Author": "xiao-min Yu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Hapoel (12.60.4)"
    },
    "549047": {
       "Type": "work_item",
       "Name": "[To Fix] [tech] move test related modules of mqm-test-box out of the main application code",
       "Id": "549047",
       "Last_Modified": "2019-08-20T15:14:59Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Yamin Hijazi",
       "Phase": "New",
       "Severity": "Low",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Yuri Guller",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Gent (12.55.17)"
    },
    "848128": {
       "Type": "work_item",
       "Name": "After adding release on Pipeline filter the Milestone filter changes position",
       "Id": "848128",
       "Last_Modified": "2019-07-29T08:29:37Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "Low",
       "Parent": "#786047 - Link automated runs injected via pipelines to Milestones",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "875008": {
       "Type": "work_item",
       "Name": "Copy of \"Reg_Munich_Push3\" Cannot filter Pipeline with Tester/Viewer only role",
       "Id": "875008",
       "Last_Modified": "2019-07-26T11:22:50Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "876006": {
       "Type": "work_item",
       "Name": "Copy of Milestone field on pipeline should be off according to experiment: link_test_run_to_milestone",
       "Id": "876006",
       "Last_Modified": "2019-07-26T08:48:45Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Nir Yom Tov",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#786047 - Link automated runs injected via pipelines to Milestones",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "880001": {
       "Type": "work_item",
       "Name": "Dialog name should be written as: \"Generate document report\" (just first word with a capital letter)",
       "Id": "880001",
       "Last_Modified": "2019-08-12T11:25:46Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Ohad Samet",
       "Phase": "Closed",
       "Severity": "Low",
       "Parent": "#786205 - [Document Report] Define report settings that include flat entities, filter, sorted fields and presentation mode for each entity",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Zvi Fried",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "853079": {
       "Type": "work_item",
       "Name": "Automated test failed: setTestFieldsOnPipeline[MT #191074][OCD Samet]",
       "Id": "853079",
       "Last_Modified": "2019-08-15T09:40:22Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Moshe Golan",
       "Phase": "New",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Author": "Iulia Andreicut",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Munich Bayern"
    },
    "876125": {
       "Type": "work_item",
       "Name": "commit injection in pipeline run failed because of commit message length been longer than 255 characters",
       "Id": "876125",
       "Last_Modified": "2019-08-11T11:59:27Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Closed",
       "Severity": "High",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Alex Shnayder",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    },
    "881040": {
       "Type": "work_item",
       "Name": "Commit name is not displayed if longer than 223 characters",
       "Id": "881040",
       "Last_Modified": "2019-08-21T06:29:44Z",
       "Blocked": "False",
       "Subtype": "defect",
       "Owner": "Elena Fradkin",
       "Phase": "Rejected",
       "Severity": "Medium",
       "Parent": "#1001 - Requirement Backlog",
       "Milestone": "Push01 (15.0.8)",
       "Author": "Mihai Muresanu",
       "Release": "Manchester-United",
       "Team": "Samet - XMen Cyclops",
       "Detected_In_Release": "Manchester-United"
    }
 }
     
 //////////////////////////////////////////////////////////////    
 function trClicked(elem) {
     var table = document.getElementById('mainTable');
     for (var i = 1, row; row = table.rows[i]; i++) {
         row.style['background-color'] = '';
     }
     elem.style['background-color'] = '#0783e0';
     var hid = document.getElementById('hiddenDiv');
     hid.innerText = elem.cells[0].innerText;
 }
 var filterList = {};
 
 function handleNewfilter(colNum, value, type) {
     var input, filter;
     if (type === 'text') {
         input = document.getElementById(value);
         filter = input.value.toUpperCase();
         if (filter === '' || !filter) {
             delete(filterList[colNum]);
         } else {
             filterList[colNum] = filter;
         }
     } else if (type === 'select') {
         filter = value.toUpperCase();
         if ('[ALL]'.indexOf(filter) > -1) {
             delete(filterList[colNum]);
         } else {
             filterList[colNum] = filter;
         }
     }
     refreshFilter();
 }
 
 function refreshFilter() {
     var totalCount = 0;
     var table = document.getElementById('mainTable');
     tr = table.getElementsByTagName('tr');
     for (i = 0; i < tr.length; i++) {
         var shouldHide = false;
         for (var key in filterList) {
             if (!shouldHide) {
                 td = tr[i].getElementsByTagName('td')[key];
                 if (td) {
                     txtValue = td.textContent || td.innerText;
                     if (txtValue.toUpperCase().indexOf(filterList[key]) < 0) {
                         shouldHide = true;
                     }
                 }
             }
         }
         if (!shouldHide) {
             tr[i].style.display = '';
             totalCount++;
         } else {
             tr[i].style.display = 'none';
         }
     }
     setTotalCount(totalCount);
 }
 
 function setTotalCount(totalCountVal) {
     var totalCount = document.getElementById('totalCount');
     if (totalCountVal) {
         totalCount.textContent = 'Total Items: ' + (totalCountVal - 1);
     } else {
         var table = document.getElementById('mainTable');
         totalCount.textContent = 'Total Items: ' + (table.getElementsByTagName('tr').length - 1);
     }
     calcRowAmount();
 }
 
 function clearFilter() {
     filterList = {};
     refreshFilter();
     var table = document.getElementById('mainTable');
     var textFilter = table.getElementsByClassName('textFilter');
     for (i = 0; i < textFilter.length; i++) {
         textFilter[i].value = '';
     }
     var selectFilter = table.getElementsByClassName('selectFilter');
     for (i = 0; i < selectFilter.length; i++) {
         selectFilter[i].options.selectedIndex = 0;
     }
 }
 
 function toggle(classToHide) {
     var hide = document.getElementsByClassName(classToHide);
     if (hide[0].style.display === 'none') {
         hide[0].style.display = '';
     } else {
         hide[0].style.display = 'none';
     }
 }
 
 function calcRowAmount() {
     var allDivs = document.getElementsByClassName('groupByDiv');
     if (allDivs) {
         for (var i = 0; i < allDivs.length; i++) {
             var rowCount = document.getElementsByClassName(allDivs[i].id);
             var rows = rowCount[0].getElementsByTagName('tr');
             var count = 0;
             for (var k = 0; k < rows.length; k++) {
                 if (rows[k].style.display !== 'none') {
                     count++;
                 }
             }
             var elem = document.getElementById(allDivs[i].id);
             if (elem && !(elem.getAttribute('originalText'))) {
                 elem.setAttribute('originalText', elem.innerHTML);
             }
             elem.innerHTML = elem.getAttribute('originalText') + (' (' + count + ')');
         }
     }
 }
 
 var currentInterval;
 function calcInfoPosition(cur) {
   floatingDivIn();
   var floatElem = document.getElementById('floatingDiv');
     floatElem.style.display = '';
     var curElem = document.getElementById(cur);
     floatElem.style.top = curElem.getBoundingClientRect().top + curElem.getBoundingClientRect().height + 'px';
     floatElem.style.left = curElem.getBoundingClientRect().left + curElem.getBoundingClientRect().width + 'px';
   setFloatingDivContent(floatElem, cur.split('_')[1]);
 }
 
 function floatingDivIn(){
   if (currentInterval) {
     clearInterval(currentInterval);
   }
 }
 
 function hideInfo() {
   currentInterval=setInterval(()=> {
       document.getElementById('floatingDiv').style.display = 'none';
   }, 3000);
 }
 
 function setFloatingDivContent(floatElem, workItemId) {
   var workitemFields = wiMap[workItemId];
   console.log(workitemFields);
   var content='';
   for (var key in workitemFields){
     content += "<div class='fieldsContainer'><div class='fieldValueContainer'><div class='fieldName'>"+key+":</div><div class='fieldValue'>"+workitemFields[key]+"</div></div></div>"
   }
   floatElem.innerHTML =content;
   
 }